[package]
name = "velovision-pi-cam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"
systemctl = "0.3.0"
tiny_http = "0.12.0"
